### ISSUE TITLE
Schedule Tab

### ISSUE THREAD

**Issue by dwd0005** [dwd0005/NativeAndroidApp#6]
## Story
As a Spur Worker, I want a one-stop shop for managing my schedule and past work so I can more easily manage my work-life.

## Issue 
Our main responsibility as an app is to help our workers track and submit their time - we need this page to be crazy-awesome.

## Acceptance Criteria
- [ ] Punch Interaction and Storage is :chefkiss:
- [ ] Calendar view is interactive and looks fly
- [ ] Shift Timeline displays live updates and is performant as a mahfk
- [ ] Job Details lazy load and expand on user request quicker than you can blink, son
- [ ] Shift Time Adjustments sings so sweet
- [ ] Job Ratings update on the fly and look so dope
- [ ] Shift Cancellation interaction let's users know what they're doing to all their buds

## UX Assets and Notes
https://sketch.cloud/s/djnVL

## Stakeholders
- Donnie
- Prince of Darkness
